<?php

/**
 * Implementation of hook_entity_type_alter()
 *
 * Override the Node class provided by core with a custom
 * impelementation for Glazed Buidler, that allows for overriding
 * of specific entity functionality
 */
function glazed_commerce_entity_type_alter(array &$entity_types) {
  $commerce_product = &$entity_types['commerce_product'];
  $commerce_product->setClass('Drupal\glazed_commerce\Entity\Product');

}
